### ISSUE TITLE
Clear git history

### ISSUE THREAD

**Issue by brunoborges** [JonathanGiles/azure-javadocs#1]
The repository has become huge. Given you don't care about the past content on `gh-pages` repository, can you delete all commits from that branch except the latest commit?

**Comment by brunoborges** [comment]
You can use something like this: `git branch new_branch_name $(echo "commit message" | git commit-tree HEAD^{tree})`

Source: https://stackoverflow.com/questions/9683279/make-the-current-commit-the-only-initial-commit-in-a-git-repository

**Comment by JonathanGiles** [comment]
Done - and about to update readme to say this is staying around for historical reasons only.
